### ISSUE TITLE
[1.1] Radio Error

### ISSUE THREAD

**Issue by blt950** [Chessnut/hl2rp#73] opened 2015-03-28 18:18 UTC
I'm having a radio error that randomly comes up. Once it works all fine, then it suddenly stops working for everyone and so on. This errors prints on each time someone uses radio when it's in broken state.

```
[ERROR] gamemodes/hl2rp/plugins/radio/sh_plugin.lua:209: attempt to index a nil value
  1. onCanHear - gamemodes/hl2rp/plugins/radio/sh_plugin.lua:209
   2. send - gamemodes/nutscript/gamemode/core/libs/sh_chatbox.lua:155
    3. Run - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:237
     4. unknown - gamemodes/nutscript/plugins/chatbox/sh_plugin.lua:69
      5. func - gamemodes/nutscript/gamemode/core/libs/external/sh_netstream2.lua:117
       6. unknown - lua/includes/modules/net.lua:32
```

**Comment by NDKilla** [comment] 2015-05-26 22:44
Can easily replicate the issue. I get this issue every single time someone tries to /radio where they're the only person on that frequency. I googled the issue and updated the sh_plugin.lua file with something I found in a patch on the /nutscript/ thing, but it only temporarily fixed it..

**Comment by Chessnut** [comment] 2015-07-03 03:54
Duplicate of #62

**Closed as completed by Chessnut** 2015-07-03 03:54 UTC
