### ISSUE TITLE
[REQUEST] Combine Forcefield / Doortitles /Doorgroups

### ISSUE THREAD

**Issue by KaiNW** [Chessnut/hl2rp#13] opened 2014-01-31 11:39 UTC
I got totay an Idea for... a little bit better HL2RP:
1. Combine-only passable Forcefield, that means (like in the original HL2) the forcefields are passable by combine.
2. Set "Main" Doortitles as non-owner/admin for Example C17 industrial, Grizzly grotto, next line custom text from door owner.
3. Doorgroups for Factions ex: Workers Union clubhouse doors, or anything like that

**Comment by Chessnut** [comment] 2014-02-01 04:27
1. Can be implemented as a plugin.
2. Will come in a new update.
3. Duplicate of class doors.

**Closed as completed by Chessnut** 2014-02-01 04:27 UTC
